# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf59516ff2b51ac5a61ab4544899bab2f41754137f85ca59048327f0b9d8537ee26b849a65d098ba153cb61c36ade36243e3fe2de7e1fc56fd78da2f53d73cdd

test:
  secret_key_base: a6e82ef774bec65a9d851659025fa1d4076d5f32c997877331e012e1f4b5985441d82f01fafdb939c4536f39bc6484f8c86f071b7379ac3ba2e6a8af904c928c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
